CREATE DATABASE SHOPEE
GO
USE SHOPEE
GO

CREATE TABLE ACCOUNT (
    ID INT NOT NULL,
    USERNAME VARCHAR(100) NOT NULL,
    [PASSWORD] VARCHAR(100) NOT NULL,
    [NAME] NVARCHAR(50) NOT NULL,
    EMAIL VARCHAR(100),
    PHONENUMBER CHAR(10) NOT NULL,
    BIRTHDAY DATE,
    [TYPE] BIT NOT NULL -- 0: normal user, 1: shop manager
)
ALTER TABLE ACCOUNT ADD CONSTRAINT pk_account PRIMARY KEY(ID)

CREATE TABLE SHOP (
    ID INT NOT NULL,
    [NAME] NVARCHAR(100) NOT NULL,
    TAXID INT NOT NULL,
    [ADDRESS] NVARCHAR(150) NOT NULL,
    PHONENUMBER CHAR(10) NOT NULL,
    EMAIL VARCHAR(100),
    ACCOUNTID INT
)
ALTER TABLE SHOP ADD CONSTRAINT pk_shop PRIMARY KEY(ID)
ALTER TABLE SHOP ADD CONSTRAINT fk_shop_account FOREIGN KEY (ACCOUNTID) REFERENCES ACCOUNT(ID)

CREATE TABLE PRODUCT (
    ID INT NOT NULL,
    [NAME] NVARCHAR(100) NOT NULL,
    [DESCRIPTION] NVARCHAR(MAX),
    SHOPID INT NOT NULL
)
ALTER TABLE PRODUCT ADD CONSTRAINT pk_product PRIMARY KEY(ID)
ALTER TABLE PRODUCT ADD CONSTRAINT fk_product_shop FOREIGN KEY(SHOPID) REFERENCES SHOP(ID)

CREATE TABLE PRODUCTTYPE (
    ID INT NOT NULL,
    [NAME] NVARCHAR(100) NOT NULL,
    QUANTITY INT NOT NULL,
    PRICE INT NOT NULL,
    [IMAGE] VARBINARY(MAX),
    PRODUCTID INT NOT NULL
)
ALTER TABLE PRODUCTTYPE ADD CONSTRAINT pk_producttype PRIMARY KEY(ID)
ALTER TABLE PRODUCTTYPE ADD CONSTRAINT fk_producctype_produuct FOREIGN KEY(PRODUCTID) REFERENCES PRODUCT(ID)

CREATE TABLE CART (
    ACCOUNTID INT NOT NULL,
    PRODUCTTYPEID INT NOT NULL,
    QUANTITY INT NOT NULL,
)
ALTER TABLE CART ADD CONSTRAINT pk_cart PRIMARY KEY(ACCOUNTID, PRODUCTTYPEID)
ALTER TABLE CART ADD CONSTRAINT fk_cart_account FOREIGN KEY(ACCOUNTID) REFERENCES ACCOUNT(ID)
ALTER TABLE CART ADD CONSTRAINT fk_cart_producttype FOREIGN KEY(PRODUCTTYPEID) REFERENCES PRODUCTTYPE(ID)

CREATE TABLE VOUCHER (
    ID INT NOT NULL,
    SHOPID INT NOT NULL,
    DISCOUNTBYNUMBER INT,
    DISCOUNTBYPERCENT INT,
    EXPIRED DATETIME NOT NULL,
    MINPRICE INT,
    MAXDISCOUNT INT
)
ALTER TABLE VOUCHER ADD CONSTRAINT pk_voucher PRIMARY KEY(ID)
ALTER TABLE VOUCHER ADD CONSTRAINT fk_voucher_shop FOREIGN KEY(SHOPID) REFERENCES SHOP(ID)

CREATE TABLE [ORDER] (
    ID INT NOT NULL,
    ACCOUNTID INT NOT NULL,
    PRODUCTTYPEID INT NOT NULL,
    QUANTITY INT NOT NULL,
    VOUCHERID INT NOT NULL,
    PAY BIT NOT NULL, -- 0: Trả sau, 1: Trả trước
    TOTAL INT NOT NULL,
    [ADDRESS] NVARCHAR(150) NOT NULL,
    SELLTIME DATETIME NOT NULl,
    [STATUS] INT NOT NULL -- 0: Waiting, 1: Accepted, 2: Cancelled
)
ALTER TABLE [ORDER] ADD CONSTRAINT pk_order PRIMARY KEY(ID)
ALTER TABLE [ORDER] ADD CONSTRAINT fk_order_account FOREIGN KEY(ACCOUNTID) REFERENCES ACCOUNT(ID)
ALTER TABLE [ORDER] ADD CONSTRAINT fk_order_producttype FOREIGN KEY(PRODUCTTYPEID) REFERENCES PRODUCTTYPE(ID)
ALTER TABLE [ORDER] ADD CONSTRAINT fk_order_voucher FOREIGN KEY(VOUCHERID) REFERENCES VOUCHER(ID)
